### ISSUE TITLE
Cordova vs PhoneGap CLI is too confusing

### ISSUE THREAD

**Issue by brodybits** [apache/cordova-discuss#79]
From #PgDay USA (NYC) 2017: Sometimes we have to use Cordova CLI, sometimes we have to use PhoneGap CLI, depending on who wrote the directions for a tutorial or workshop. This is getting too confusing, please separate when to use Cordova vs PhoneGap tools. For example: Cordova CLI for basic tasks such as prepare/build/run project in a work area, PhoneGap CLI for more specialized items such as running in PhoneGap developer app.

In specific terms: *please* deprecate PhoneGap CLI.

It is my understanding from @macdonst that PhoneGap CLI uses the exact same library code as Cordova CLI per version which is already good progress. Hope to see the final end of this mess.

**Comment by janpio** [comment]
What can Cordova do to fix this?

**Comment by jcesarmobile** [comment]
Phonegap day is organized by Phonegap people, and some of the workshops are organized by Phonegap people too, so I understand they prefer to use Phonegap CLI instead of Cordova CLI, specially if they want to show the few features Cordova CLI doesn't include. 

Phonegap belongs to Adobe, so better get in touch with them, there is nothing we can do about it on the cordova side.
