### ISSUE TITLE
Archive deprecated repos

### ISSUE THREAD

**Issue by raphinesse** [apache/cordova-discuss#92]
I propose to [archive](https://help.github.com/articles/archiving-repositories/) any deprecated repos.

To still be able to easily point people to maintained forks we could add a link to a central Wiki page (for example in `apache/cordova`) that lists up-to-date information on deprecated projects. Something along the lines of:

> This project is **DEPRECATED**. For up-to-date information and possible alternatives see LINK.

**Comment by jcesarmobile** [comment]
Most of the plugins are deprecated for good (because there are browser alternatives), so the only one I can think about is contacts plugin that might need this (and just in case somebody forks it and maintain it).

So I'm +1 on archiving and don't worry about them anymore and don't track possible forks.

**Comment by raphinesse** [comment]
Deprecated repos have been archived
